"""add commodity_prices table

Revision ID: 9caffb39c2d4
Revises: e9faaf5a2041
Create Date: 2026-03-12 14:11:33.852305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caffb39c2d4'
down_revision: Union[str, Sequence[str], None] = 'e9faaf5a2041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
