"""add cot_reports table

Revision ID: e9faaf5a2041
Revises: 179b717d7ad4
Create Date: 2026-03-12 13:07:29.715659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9faaf5a2041'
down_revision: Union[str, Sequence[str], None] = '179b717d7ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cot_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('contract_market_name', sa.String(length=200), nullable=False),
    sa.Column('cftc_contract_market_code', sa.String(length=20), nullable=False),
    sa.Column('commodity_name', sa.String(length=100), nullable=False),
    sa.Column('commodity_group', sa.String(length=20), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('prod_merc_long', sa.Integer(), nullable=True),
    sa.Column('prod_merc_short', sa.Integer(), nullable=True),
    sa.Column('swap_long', sa.Integer(), nullable=True),
    sa.Column('swap_short', sa.Integer(), nullable=True),
    sa.Column('swap_spread', sa.Integer(), nullable=True),
    sa.Column('m_money_long', sa.Integer(), nullable=True),
    sa.Column('m_money_short', sa.Integer(), nullable=True),
    sa.Column('m_money_spread', sa.Integer(), nullable=True),
    sa.Column('other_rept_long', sa.Integer(), nullable=True),
    sa.Column('other_rept_short', sa.Integer(), nullable=True),
    sa.Column('other_rept_spread', sa.Integer(), nullable=True),
    sa.Column('nonrept_long', sa.Integer(), nullable=True),
    sa.Column('nonrept_short', sa.Integer(), nullable=True),
    sa.Column('change_open_interest', sa.Integer(), nullable=True),
    sa.Column('change_prod_merc_long', sa.Integer(), nullable=True),
    sa.Column('change_prod_merc_short', sa.Integer(), nullable=True),
    sa.Column('change_swap_long', sa.Integer(), nullable=True),
    sa.Column('change_swap_short', sa.Integer(), nullable=True),
    sa.Column('change_m_money_long', sa.Integer(), nullable=True),
    sa.Column('change_m_money_short', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', 'cftc_contract_market_code', name='uq_cot_report')
    )
    op.create_index(op.f('ix_cot_reports_cftc_contract_market_code'), 'cot_reports', ['cftc_contract_market_code'], unique=False)
    op.create_index(op.f('ix_cot_reports_commodity_group'), 'cot_reports', ['commodity_group'], unique=False)
    op.create_index(op.f('ix_cot_reports_commodity_name'), 'cot_reports', ['commodity_name'], unique=False)
    op.create_index(op.f('ix_cot_reports_contract_market_name'), 'cot_reports', ['contract_market_name'], unique=False)
    op.create_index(op.f('ix_cot_reports_report_date'), 'cot_reports', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cot_reports_report_date'), table_name='cot_reports')
    op.drop_index(op.f('ix_cot_reports_contract_market_name'), table_name='cot_reports')
    op.drop_index(op.f('ix_cot_reports_commodity_name'), table_name='cot_reports')
    op.drop_index(op.f('ix_cot_reports_commodity_group'), table_name='cot_reports')
    op.drop_index(op.f('ix_cot_reports_cftc_contract_market_code'), table_name='cot_reports')
    op.drop_table('cot_reports')
    # ### end Alembic commands ###
